# Generated by Django 4.2.18 on 2025-01-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='parcela_atual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
